services:
  - type: web
    name: video-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app # Zmień na komendę startową Twojej aplikacji (np. python bot.py)
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0